"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

export type Language = "vi" | "en";

const dictionaries: Record<Language, Record<string, string>> = {
  vi: {
    "app.subtitle": "Hệ thống quản lý",
    "common.cancel": "Hủy",
    "common.saveChanges": "Lưu thay đổi",
    "common.saving": "Đang lưu...",
    "common.savedSettings": "Đã lưu cài đặt.",
    "common.restoreSettings": "Đã khôi phục cài đặt trước đó.",
    "common.saveSettingsError": "Không thể lưu cài đặt.",
    "common.createNew": "Tạo mới",
    "common.user": "Người dùng",
    "common.admin": "Admin",
    "common.openMenu": "Mở menu",
    "common.search": "Tìm kiếm",
    "common.profile": "Hồ sơ cá nhân",
    "common.notifications": "Thông báo",
    "common.help": "Trợ giúp",
    "nav.main": "Chính",
    "nav.organization": "Tổ chức",
    "nav.analytics": "Phân tích",
    "nav.system": "Hệ thống",
    "nav.adminGroup": "Quản trị viên",
    "nav.dashboard": "Tổng quan",
    "nav.myCalendar": "Lịch của tôi",
    "nav.reminders": "Nhắc việc",
    "nav.tags": "Tags",
    "nav.templates": "Templates",
    "nav.share": "Chia sẻ",
    "nav.statistics": "Thống kê",
    "nav.history": "Lịch sử",
    "nav.importExport": "Nhập & Xuất",
    "nav.settings": "Cài đặt",
    "nav.admin": "Quản trị",
    "topbar.searchPlaceholder": "Tìm kiếm công việc, sự kiện...",
    "dashboard.greeting.late": "Khuya rồi",
    "dashboard.greeting.morning": "Chào buổi sáng",
    "dashboard.greeting.noon": "Chào buổi trưa",
    "dashboard.greeting.afternoon": "Chào buổi chiều",
    "dashboard.greeting.evening": "Chào buổi tối",
    "dashboard.summary.prefix": "Hôm nay bạn có",
    "dashboard.summary.events": "sự kiện",
    "dashboard.summary.and": "và",
    "dashboard.summary.tasksNeedAttention": "nhiệm vụ cần chú ý.",
    "dashboard.summary.streakSuffix": "ngày liên tiếp",
    "dashboard.stat.today": "Hôm nay",
    "dashboard.stat.todaySub": "sự kiện cần thực hiện",
    "dashboard.stat.overdue": "Quá hạn",
    "dashboard.stat.tasks": "nhiệm vụ",
    "dashboard.stat.next7Days": "7 ngày tới",
    "dashboard.stat.events": "sự kiện",
    "dashboard.stat.completed": "Hoàn thành",
    "dashboard.stat.total": "tổng số",
    "dashboard.stat.reminders": "Nhắc việc",
    "dashboard.stat.enabled": "đang bật",
    "dashboard.timeline.title": "Lịch trình hôm nay",
    "dashboard.empty.title": "Bạn chưa có sự kiện nào hôm nay",
    "dashboard.empty.desc": "Hãy tạo lịch đầu tiên để bắt đầu quản lý công việc hiệu quả hơn. Mọi việc sẽ được nhắc nhở tự động qua Mezon.",
    "dashboard.empty.cta": "Tạo lịch đầu tiên",
    "dashboard.calendar.previousMonth": "Tháng trước",
    "dashboard.calendar.nextMonth": "Tháng sau",
    "dashboard.calendar.viewDay": "Xem lịch ngày",
    "dashboard.priority.title": "Ưu tiên cao",
    "dashboard.priority.viewAll": "Xem tất cả nhiệm vụ",
    "dashboard.deadline.title": "Sắp đến hạn",
    "dashboard.deadline.prefix": "Còn",
    "dashboard.deadline.day": "ngày",
    "dashboard.deadline.label": "Deadline",
    "dashboard.typeDistribution.title": "Phân bổ theo loại",
    "dashboard.typeDistribution.empty": "Chưa có lịch nào để thống kê.",
    "dashboard.typeDistribution.total": "TỔNG SỐ",
    "dashboard.type.task": "Công việc",
    "dashboard.type.meeting": "Cuộc họp",
    "dashboard.type.event": "Sự kiện",
    "dashboard.type.reminder": "Nhắc việc",
    "settings.title": "Cài đặt cá nhân",
    "settings.subtitle": "Quản lý các tùy chọn hệ thống và thông tin cá nhân của bạn.",
    "settings.tab.general": "Chung",
    "settings.tab.notification": "Thông báo",
    "settings.tab.integration": "Tích hợp",
    "settings.tab.template": "Mẫu",
    "settings.general.title": "Cài đặt chung",
    "settings.timezone": "Múi giờ",
    "settings.timezoneHelp": "Thời gian hiển thị trên toàn ứng dụng.",
    "settings.language": "Ngôn ngữ",
    "settings.vietnamese": "Tiếng Việt",
    "settings.english": "English",
    "settings.theme": "Giao diện",
    "settings.light": "Sáng",
    "settings.dark": "Tối",
    "settings.workHours": "Giờ làm việc",
    "settings.workHoursDesc": "Xác định thời gian bạn sẵn sàng để đồng nghiệp có thể xếp lịch họp phù hợp.",
    "settings.start": "Bắt đầu",
    "settings.end": "Kết thúc",
    "settings.notificationChannel": "Kênh nhận thông báo mặc định",
    "settings.notificationChannelDesc": "Chọn nơi bạn muốn nhận các nhắc nhở sự kiện",
    "settings.browser": "Trình duyệt",
    "settings.email": "Email",
    "settings.both": "Cả hai",
    "settings.mezonMode": "Nhận qua DM hay Channel",
    "settings.mezonModeDesc": "Phân loại tin nhắn thông báo trong hệ thống Mezon",
    "settings.defaultReminder": "Nhắc trước mặc định",
    "settings.defaultReminderDesc": "Khoảng thời gian nhắc nhở trước khi bắt đầu",
    "settings.minutes": "phút",
    "settings.integrationTitle": "Tích hợp",
    "settings.connected": "Đang kết nối",
    "settings.configMezon": "Cấu hình Mezon",
    "settings.mezonDesc": "Kết nối tài khoản Mezon để đồng bộ danh sách liên lạc và gửi thông báo trực tiếp qua kênh hội thoại.",
    "settings.mezonConfigEnv": "Mezon đang được cấu hình bằng biến môi trường backend.",
    "settings.integrationUnavailableSuffix": " chưa có backend tích hợp trong dự án này.",
    "settings.tipTitle": "Mẹo năng suất",
    "settings.tipText": "Thiết lập giờ làm việc giúp bạn tránh bị làm phiền bởi các cuộc họp ngoài khung giờ cá nhân.",
    "settings.templatesDesc": "Quản lý các mẫu mặc định cho sự kiện mới.",
    "settings.edit": "Chỉnh sửa",
    "settings.addTemplate": "+ Thêm mẫu mới",
    "settings.connectedStatus": "Đã kết nối",
    "settings.connect": "Kết nối",
    "settings.day.mon": "Thứ 2",
    "settings.day.tue": "Thứ 3",
    "settings.day.wed": "Thứ 4",
    "settings.day.thu": "Thứ 5",
    "settings.day.fri": "Thứ 6",
    "settings.day.sat": "Thứ 7",
    "settings.day.sun": "CN",
  },
  en: {
    "app.subtitle": "Management system",
    "common.cancel": "Cancel",
    "common.saveChanges": "Save changes",
    "common.saving": "Saving...",
    "common.savedSettings": "Settings saved.",
    "common.restoreSettings": "Previous settings restored.",
    "common.saveSettingsError": "Could not save settings.",
    "common.createNew": "Create new",
    "common.user": "User",
    "common.admin": "Admin",
    "common.openMenu": "Open menu",
    "common.search": "Search",
    "common.profile": "Personal profile",
    "common.notifications": "Notifications",
    "common.help": "Help",
    "nav.main": "Main",
    "nav.organization": "Organization",
    "nav.analytics": "Analytics",
    "nav.system": "System",
    "nav.adminGroup": "Administrator",
    "nav.dashboard": "Overview",
    "nav.myCalendar": "My calendar",
    "nav.reminders": "Reminders",
    "nav.tags": "Tags",
    "nav.templates": "Templates",
    "nav.share": "Share",
    "nav.statistics": "Statistics",
    "nav.history": "History",
    "nav.importExport": "Import & Export",
    "nav.settings": "Settings",
    "nav.admin": "Admin",
    "topbar.searchPlaceholder": "Search tasks and events...",
    "dashboard.greeting.late": "Working late",
    "dashboard.greeting.morning": "Good morning",
    "dashboard.greeting.noon": "Good afternoon",
    "dashboard.greeting.afternoon": "Good afternoon",
    "dashboard.greeting.evening": "Good evening",
    "dashboard.summary.prefix": "Today you have",
    "dashboard.summary.events": "events",
    "dashboard.summary.and": "and",
    "dashboard.summary.tasksNeedAttention": "tasks that need attention.",
    "dashboard.summary.streakSuffix": "day streak",
    "dashboard.stat.today": "Today",
    "dashboard.stat.todaySub": "events to complete",
    "dashboard.stat.overdue": "Overdue",
    "dashboard.stat.tasks": "tasks",
    "dashboard.stat.next7Days": "Next 7 days",
    "dashboard.stat.events": "events",
    "dashboard.stat.completed": "Completed",
    "dashboard.stat.total": "total",
    "dashboard.stat.reminders": "Reminders",
    "dashboard.stat.enabled": "enabled",
    "dashboard.timeline.title": "Today's schedule",
    "dashboard.empty.title": "You have no events today",
    "dashboard.empty.desc": "Create your first schedule to start managing work more effectively. Reminders will be sent automatically through Mezon.",
    "dashboard.empty.cta": "Create first schedule",
    "dashboard.calendar.previousMonth": "Previous month",
    "dashboard.calendar.nextMonth": "Next month",
    "dashboard.calendar.viewDay": "View schedule for",
    "dashboard.priority.title": "High priority",
    "dashboard.priority.viewAll": "View all tasks",
    "dashboard.deadline.title": "Due soon",
    "dashboard.deadline.prefix": "",
    "dashboard.deadline.day": "days left",
    "dashboard.deadline.label": "Deadline",
    "dashboard.typeDistribution.title": "Distribution by type",
    "dashboard.typeDistribution.empty": "No schedules available for statistics.",
    "dashboard.typeDistribution.total": "TOTAL",
    "dashboard.type.task": "Task",
    "dashboard.type.meeting": "Meeting",
    "dashboard.type.event": "Event",
    "dashboard.type.reminder": "Reminder",
    "settings.title": "Personal settings",
    "settings.subtitle": "Manage system preferences and your personal information.",
    "settings.tab.general": "General",
    "settings.tab.notification": "Notifications",
    "settings.tab.integration": "Integrations",
    "settings.tab.template": "Templates",
    "settings.general.title": "General settings",
    "settings.timezone": "Time zone",
    "settings.timezoneHelp": "Display time across the application.",
    "settings.language": "Language",
    "settings.vietnamese": "Vietnamese",
    "settings.english": "English",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.workHours": "Working hours",
    "settings.workHoursDesc": "Set the time you are available so teammates can schedule meetings appropriately.",
    "settings.start": "Start",
    "settings.end": "End",
    "settings.notificationChannel": "Default notification channel",
    "settings.notificationChannelDesc": "Choose where you want to receive event reminders",
    "settings.browser": "Browser",
    "settings.email": "Email",
    "settings.both": "Both",
    "settings.mezonMode": "Receive via DM or Channel",
    "settings.mezonModeDesc": "Choose how reminder messages are routed in Mezon",
    "settings.defaultReminder": "Default reminder",
    "settings.defaultReminderDesc": "Reminder lead time before an event starts",
    "settings.minutes": "minutes",
    "settings.integrationTitle": "Integrations",
    "settings.connected": "Connected",
    "settings.configMezon": "Configure Mezon",
    "settings.mezonDesc": "Connect your Mezon account to sync contacts and send reminders directly through chat channels.",
    "settings.mezonConfigEnv": "Mezon is configured through backend environment variables.",
    "settings.integrationUnavailableSuffix": " does not have a backend integration in this project yet.",
    "settings.tipTitle": "Productivity tip",
    "settings.tipText": "Working hours help you avoid meeting reminders outside your personal availability.",
    "settings.templatesDesc": "Manage default templates for new events.",
    "settings.edit": "Edit",
    "settings.addTemplate": "+ Add new template",
    "settings.connectedStatus": "Connected",
    "settings.connect": "Connect",
    "settings.day.mon": "Mon",
    "settings.day.tue": "Tue",
    "settings.day.wed": "Wed",
    "settings.day.thu": "Thu",
    "settings.day.fri": "Fri",
    "settings.day.sat": "Sat",
    "settings.day.sun": "Sun",
  },
};

const hardcodedViToEn: Record<string, string> = {
  "Đang tải...": "Loading...",
  "Đang tải dữ liệu...": "Loading data...",
  "Không có dữ liệu": "No data",
  "Không có lịch nào": "No schedules",
  "Không có user phù hợp.": "No matching users.",
  "Tạo mới": "Create new",
  "Tạo lịch mới": "Create schedule",
  "Tạo lịch đầu tiên": "Create first schedule",
  "Thêm lịch trình mới": "Add new schedule",
  "Lưu": "Save",
  "Lưu thay đổi": "Save changes",
  "Đang lưu...": "Saving...",
  "Hủy": "Cancel",
  "Hủy bỏ": "Cancel",
  "Xóa": "Delete",
  "Xóa mẫu": "Delete template",
  "Xác nhận xóa": "Confirm delete",
  "Chi tiết": "Details",
  "Chỉnh sửa": "Edit",
  "Chỉnh sửa sự kiện": "Edit event",
  "Hoàn thành": "Complete",
  "Đã hoàn thành": "Completed",
  "Lưu sự kiện": "Save event",
  "Tìm kiếm": "Search",
  "Tìm kiếm câu hỏi...": "Search questions...",
  "Tìm kiếm lịch trình": "Search schedules",
  "Tìm kiếm lịch": "Search schedules",
  "Tất cả": "All",
  "Đang chờ": "Pending",
  "Đã hủy": "Cancelled",
  "Cao": "High",
  "Vừa": "Medium",
  "Thấp": "Low",
  "Trung bình": "Medium",
  "Công việc": "Work",
  "Cá nhân": "Personal",
  "Quan trọng": "Important",
  "Học tập": "Study",
  "Cuộc họp": "Meeting",
  "Sự kiện": "Event",
  "Nhắc việc": "Reminder",
  "Lịch sắp tới": "Upcoming schedules",
  "24 giờ": "24 hours",
  "7 ngày": "7 days",
  "Lịch của tôi": "My calendar",
  "Xuất dữ liệu": "Export data",
  "Xuất lịch trình": "Export schedules",
  "Chọn định dạng xuất": "Choose export format",
  "Bộ lọc xuất": "Export filters",
  "Khoảng thời gian": "Date range",
  "Từ ngày": "From date",
  "Đến ngày": "To date",
  "Trạng thái": "Status",
  "Mức ưu tiên": "Priority",
  "Mức độ ưu tiên": "Priority",
  "Xuất file": "Export file",
  "Xuất nhật ký": "Export log",
  "Lịch sử thay đổi": "Change history",
  "Theo dõi tất cả các hành động trên hệ thống.": "Track all actions in the system.",
  "Cập nhật": "Update",
  "Mô tả chi tiết": "Detailed description",
  "Thời gian": "Time",
  "Bắt đầu": "Start",
  "Kết thúc": "End",
  "Gắn thẻ": "Tags",
  "+ Thêm": "+ Add",
  "+ Thêm tag": "+ Add tag",
  "Mời": "Invite",
  "Người tham gia": "Participants",
  "Tắt nhắc": "Disable reminder",
  "Nhân bản": "Duplicate",
  "Bật/Tắt lặp": "Toggle recurrence",
  "Chia sẻ lịch": "Share schedule",
  "Thông tin cơ bản": "Basic information",
  "Loại sự kiện": "Event type",
  "Tiêu đề": "Title",
  "Mô tả": "Description",
  "Thời gian thực hiện": "Schedule time",
  "Tùy chọn nâng cao": "Advanced options",
  "Thời gian nhắc nhở": "Reminder time",
  "Lặp lại": "Repeat",
  "Không lặp lại": "Do not repeat",
  "Hàng ngày": "Daily",
  "Hàng tuần": "Weekly",
  "Hàng tháng": "Monthly",
  "Không": "None",
  "Nhắc gần nhất": "Latest reminder",
  "Định kỳ": "Recurring",
  "Chia sẻ": "Share",
  "0 người": "0 people",
  "Cài đặt lịch lặp": "Recurrence settings",
  "Tần suất": "Frequency",
  "Lặp vào các ngày": "Repeat on days",
  "Không bao giờ": "Never",
  "Vào ngày": "On date",
  "Sau số lần": "After count",
  "Lưu cài đặt lặp": "Save recurrence",
  "Trung tâm trợ giúp": "Help center",
  "Tìm câu trả lời nhanh và hướng dẫn sử dụng.": "Find quick answers and usage guides.",
  "Câu hỏi thường gặp": "FAQ",
  "Liên kết nhanh": "Quick links",
  "Hướng dẫn bắt đầu": "Getting started",
  "Video hướng dẫn": "Video tutorials",
  "Liên hệ hỗ trợ": "Contact support",
  "Lệnh Mezon Bot": "Mezon bot commands",
  "Hồ sơ cá nhân": "Personal profile",
  "Thông báo": "Notifications",
  "Nhập & Xuất": "Import & Export",
  "Thống kê": "Statistics",
  "Lịch sử": "History",
  "Cài đặt": "Settings",
  "Quản trị": "Admin",
  "Quản lý người dùng": "User management",
  "Tổng": "Total",
  "Khoá": "Lock",
  "Mở khoá": "Unlock",
  "Lọc": "Filter",
  "Tạo lúc": "Created at",
  "Hành động": "Actions",
  "Hạ user": "Demote user",
  "Lên admin": "Promote admin",
  "Xoá": "Delete",
  "Trước": "Previous",
  "Sau": "Next",
  "Đã xảy ra lỗi": "Something went wrong",
  "Một lỗi không mong muốn đã xảy ra. Bạn có thể thử lại hoặc tải lại trang.": "An unexpected error occurred. You can try again or reload the page.",
  "Mã lỗi": "Error code",
  "Thử lại": "Try again",
  "Tải lại trang": "Reload page",
  "Tuyệt vời! Đã hoàn thành": "Great! Completed",
  "Tiến độ tuần này": "This week's progress",
  "Quay lại Dashboard": "Back to Dashboard",
  "Xem thống kê": "View statistics",
  "Xóa mẫu lịch?": "Delete schedule template?",
  "Xem trước mẫu": "Preview template",
  "Xóa thẻ phân loại?": "Delete category tag?",
  "Xem trước thay đổi": "Preview changes",
  "Sắp gỡ bỏ": "Will be removed",
  "Dự án A": "Project A",
  "Xóa thẻ": "Delete tag",
  "Dừng chia sẻ lịch?": "Stop sharing schedule?",
  "Dừng chia sẻ": "Stop sharing",
  "Hành động bảo mật được xác thực": "Security action verified",
  "Làm thế nào để tạo lịch mới?": "How do I create a new schedule?",
  "Nhấn nút \"Tạo mới\" ở sidebar hoặc vào trang Lịch của tôi → nhấn nút \"+\" ở góc trên. Bạn cũng có thể dùng lệnh *them-lich trên Mezon.": "Click \"Create new\" in the sidebar or open My calendar and press the \"+\" button in the top corner. You can also use the *them-lich command in Mezon.",
  "Làm sao để đặt nhắc nhở cho sự kiện?": "How do I set a reminder for an event?",
  "Mở chi tiết sự kiện → phần Nhắc nhở → chọn thời gian nhắc (15 phút, 30 phút, 1 giờ trước). Trên Mezon, dùng lệnh *nhac <ID> <phút>.": "Open event details, go to Reminders, then choose a reminder time (15 minutes, 30 minutes, 1 hour before). In Mezon, use *nhac <ID> <minutes>.",
  "Cách import lịch từ Excel?": "How do I import schedules from Excel?",
  "Vào trang Nhập & Xuất → tab Nhập dữ liệu → kéo thả file .xlsx hoặc .csv. Trên Mezon, dùng lệnh *them-lich-excel.": "Go to Import & Export, open the Import data tab, then drag in a .xlsx or .csv file. In Mezon, use *them-lich-excel.",
  "Làm sao để chia sẻ lịch với đồng nghiệp?": "How do I share a schedule with teammates?",
  "Mở chi tiết sự kiện → nhấn nút \"Chia sẻ\" → chọn người nhận từ danh bạ hoặc nhập email.": "Open event details, click Share, then choose a recipient from contacts or enter an email.",
  "Cách thiết lập lịch lặp lại?": "How do I set up a recurring schedule?",
  "Mở chi tiết sự kiện → nhấn \"Cài đặt lặp\" → chọn tần suất (hàng ngày, hàng tuần, hàng tháng) và ngày kết thúc.": "Open event details, click Recurrence settings, choose a frequency (daily, weekly, monthly), and set an end date.",
  "Làm sao kết nối với Mezon?": "How do I connect with Mezon?",
  "Vào Cài đặt → Tích hợp → nhấn \"Kết nối Mezon\". Bạn cần có tài khoản Mezon để sử dụng bot.": "Go to Settings, open Integrations, and click Connect Mezon. You need a Mezon account to use the bot.",
  "Xem lịch hôm nay": "View today's schedule",
  "Thêm lịch mới (form interactive)": "Add a new schedule (interactive form)",
  "Xem chi tiết lịch": "View schedule details",
  "Xem N lịch sắp tới": "View N upcoming schedules",
  "Xem thống kê năng suất": "View productivity statistics",
  "Hiển thị trợ giúp": "Show help",
  "Thêm nhanh lịch": "Quick add schedule",
  "Tiêu đề *": "Title *",
  "Nhập tiêu đề sự kiện...": "Enter event title...",
  "Ngày": "Date",
  "Giờ": "Time",
  "Tạo lịch": "Create schedule",
  "Chọn lịch và nhập Mezon user ID cần chia sẻ.": "Choose a schedule and enter the Mezon user ID to share with.",
  "Không chia sẻ được lịch.": "Could not share schedule.",
  "Đã chia sẻ lịch.": "Schedule shared.",
  "Người dùng này đã được chia sẻ trước đó.": "This user has already been shared with.",
  "Không thể chia sẻ lịch.": "Could not share schedule.",
  "Quản lý lịch chia sẻ và danh bạ đồng nghiệp.": "Manage shared schedules and teammate contacts.",
  "Chia sẻ lịch mới": "Share new schedule",
  "Danh bạ": "Contacts",
  "Chưa có lịch nào được chia sẻ với bạn": "No schedules have been shared with you",
  "Khi đồng nghiệp chia sẻ lịch, nó sẽ xuất hiện ở đây.": "When a teammate shares a schedule, it will appear here.",
  "Tính năng danh bạ đang phát triển": "Contacts are under development",
  "Hiện tại bạn có thể chia sẻ lịch trực tiếp bằng Mezon user ID.": "For now, you can share schedules directly by Mezon user ID.",
  "Chia sẻ quyền xem lịch cho một Mezon user ID đã từng dùng bot.": "Share schedule view access with a Mezon user ID that has used the bot.",
  "Lịch cần chia sẻ": "Schedule to share",
  "Bạn chưa có lịch để chia sẻ": "You do not have any schedules to share",
  "Đang chia sẻ...": "Sharing...",
  "Bắt đầu hành trình năng suất của bạn": "Start your productivity journey",
  "Có vẻ như bạn chưa có lịch trình nào. Hãy tạo sự kiện đầu tiên để bắt đầu quản lý thời gian hiệu quả hơn.": "It looks like you do not have any schedules yet. Create your first event to start managing time more effectively.",
  "Sử dụng mẫu (Templates)": "Use templates",
  "Chưa có Thẻ nào được tạo": "No tags have been created",
  "Sử dụng Thẻ để nhóm các sự kiện theo chủ đề như Công việc, Cá nhân hoặc Dự án, giúp bạn lọc và quản lý lịch trình khoa học hơn.": "Use tags to group events by topics like Work, Personal, or Project so you can filter and manage schedules more clearly.",
  "Tạo thẻ đầu tiên": "Create first tag",
  "Tìm hiểu thêm": "Learn more",
  "Lọc nhanh chóng": "Quick filtering",
  "Dễ dàng tìm thấy các nhiệm vụ cùng chủ đề chỉ với một cú nhấp.": "Find tasks with the same topic in one click.",
  "Màu sắc riêng biệt": "Distinct colors",
  "Phân loại bằng màu sắc giúp nhận diện danh mục ngay lập tức trên lịch.": "Color categories make them easy to recognize on the calendar.",
  "Tự động gợi ý": "Automatic suggestions",
  "Hệ thống thông minh sẽ gợi ý thẻ dựa trên nội dung bạn nhập.": "The system suggests tags based on what you enter.",
  "Bạn chưa có Mẫu lịch nào": "You do not have any schedule templates",
  "Tiết kiệm thời gian bằng cách lưu các lịch trình thường xuyên lặp lại thành mẫu. Bạn có thể tạo lịch mới chỉ với một cú nhấp chuột để duy trì tính hiệu quả và tập trung.": "Save time by turning frequently repeated schedules into templates. You can create a new schedule with one click and stay focused.",
  "Tạo mẫu đầu tiên": "Create first template",
  "Nhanh chóng": "Fast",
  "Tạo lịch mới chỉ với 1 click.": "Create a schedule in one click.",
  "Đồng bộ": "Sync",
  "Đồng bộ mẫu với Mezon bot.": "Sync templates with the Mezon bot.",
  "Chính xác": "Accurate",
  "Không sai sót khi tạo lịch.": "Avoid mistakes when creating schedules.",
  "Lỗi kết nối hệ thống": "System connection error",
  "Không thể kết nối đến máy chủ. Vui lòng kiểm tra kết nối mạng và thử lại.": "Could not connect to the server. Please check your network connection and try again.",
  "Lỗi đồng bộ Mezon": "Mezon sync error",
  "Không thể đồng bộ dữ liệu với Mezon Bot. Kết nối bot có thể đã hết hạn.": "Could not sync data with the Mezon bot. The bot connection may have expired.",
  "Kết nối lại": "Reconnect",
  "Lỗi nhập dữ liệu": "Import data error",
  "Dữ liệu không hợp lệ. Vui lòng kiểm tra lại các trường bắt buộc và định dạng.": "Invalid data. Please check required fields and formats.",
  "Lỗi tải dữ liệu": "Data loading error",
  "Không thể tải dữ liệu từ máy chủ. Vui lòng thử lại sau.": "Could not load data from the server. Please try again later.",
  "Mạng không ổn định": "Unstable network",
  "Kết nối mạng không ổn định. Một số tính năng có thể không hoạt động bình thường.": "The network connection is unstable. Some features may not work properly.",
  "Thử lại kết nối": "Retry connection",
  "Thống kê hiệu suất": "Performance statistics",
  "Dữ liệu được đồng bộ trực tiếp từ hệ thống NestJS của bạn.": "Data is synced directly from your NestJS system.",
  "7 ngày qua": "Last 7 days",
  "Xuất báo cáo": "Export report",
  "Hiệu suất hoàn thành công việc": "Task completion performance",
  "Tuần này": "This week",
  "Tuần trước": "Last week",
  "Phân bổ theo Tag": "Distribution by tag",
  "Làm việc": "Work",
  "Lịch sử thay đổi hệ thống": "System change history",
  "Xem tất cả": "View all",
  "Nhiệm vụ": "Task",
  "Tổng thời gian tập trung": "Total focus time",
  "Nhiệm vụ hoàn thành": "Completed tasks",
  "Dự án hoạt động": "Active projects",
  "Chưa có dữ liệu thống kê để xuất.": "No statistics are available to export.",
  "Đã xuất báo cáo CSV và HTML.": "CSV and HTML reports exported.",
  "Đồng bộ lịch trình, nhận nhắc nhở qua chat": "Sync schedules and receive chat reminders",
  "Đồng bộ hai chiều với Google Calendar": "Two-way sync with Google Calendar",
  "Kết nối với Microsoft Outlook Calendar": "Connect with Microsoft Outlook Calendar",
  "Nhận thông báo lịch trình qua Slack": "Receive schedule notifications through Slack",
  "Đồng bộ tasks từ Notion databases": "Sync tasks from Notion databases",
  "Cuộc họp mặc định": "Default meeting",
  "Deadline công việc": "Work deadline",
  "Sự kiện cá nhân": "Personal event",
  "30 phút": "30 minutes",
  "2 giờ": "2 hours",
  "15 phút trước": "15 minutes before",
  "30 phút trước": "30 minutes before",
  "đúng giờ": "on time",
  "Hôm nay": "Today",
  "Sắp tới": "Upcoming",
  "Nhắc nhở đang hoạt động": "Active reminders",
  "Nhắc nhở hôm nay": "Today's reminders",
  "Không có nhắc nhở nào": "No reminders",
  "Quản lý tất cả các nhắc nhở của bạn. Có": "Manage all your reminders. There are",
  "nhắc nhở đang bật.": "active reminders.",
  "Thống kê hệ thống": "System statistics",
  "Biểu đồ tăng trưởng và tỷ lệ trạng thái lịch toàn hệ thống.": "Growth charts and system-wide schedule status ratios.",
  "Đang tải…": "Loading...",
  "User đăng ký 30 ngày": "User signups in 30 days",
  "Lịch tạo 30 ngày": "Schedules created in 30 days",
  "Chưa có dữ liệu.": "No data yet.",
  "Tỷ lệ trạng thái lịch": "Schedule status ratio",
  "Audit log toàn hệ thống": "System-wide audit log",
  "Thứ 2": "Mon",
  "Thứ 3": "Tue",
  "Thứ 4": "Wed",
  "Thứ 5": "Thu",
  "Thứ 6": "Fri",
  "Thứ 7": "Sat",
  "CN": "Sun",
  "Không có bản ghi phù hợp.": "No matching records.",
  "Bật bot Mezon": "Enable Mezon bot",
  "Tắt để tạm dừng bot xử lý lệnh.": "Turn off to pause bot command processing.",
  "Cho phép đăng ký mới": "Allow new registrations",
  "Khi tắt, user mới không thể khởi tạo tài khoản.": "When off, new users cannot initialize accounts.",
  "Banner thông báo toàn site": "Site-wide notification banner",
  "Để rỗng để ẩn banner. Nhập nội dung để hiển thị banner cảnh báo / thông tin.": "Leave empty to hide the banner. Enter content to show a warning or information banner.",
  "Cấu hình hệ thống": "System configuration",
  "Bật": "On",
  "(để trống để ẩn)": "(leave empty to hide)",
  "Hiện tại": "Current",
  "Đang lưu…": "Saving...",
  "Cập nhật thành công!": "Updated successfully!",
  "Không thể cập nhật. Vui lòng thử lại.": "Could not update. Please try again.",
  "Không tìm thấy template đã chọn.": "Selected template not found.",
  "Đã nạp template vào form tạo lịch.": "Template loaded into the create schedule form.",
  "Không thể nạp template. Vui lòng thử lại.": "Could not load template. Please try again.",
  "Lịch biểu": "Schedule",
  "Thêm lịch mới": "Add new schedule",
  "Loại lịch": "Schedule type",
  "Tiêu đề sự kiện": "Event title",
  "Tên cuộc họp, hoạt động...": "Meeting name, activity...",
  "Ghi chú thêm về sự kiện này...": "Additional notes for this event...",
  "Ngày bắt đầu": "Start date",
  "Giờ bắt đầu": "Start time",
  "Ngày kết thúc": "End date",
  "Giờ kết thúc": "End time",
  "XEM TRƯỚC": "PREVIEW",
  "hàng ngày": "daily",
  "hàng tuần": "weekly",
  "hàng tháng": "monthly",
  "Tạo lịch thành công!": "Schedule created successfully!",
  "Không thể tạo lịch. Vui lòng thử lại.": "Could not create schedule. Please try again.",
  "Nhập từ khóa tìm kiếm...": "Enter search keywords...",
  "Tìm thấy": "Found",
  "kết quả cho": "results for",
  "Không tìm thấy kết quả": "No results found",
  "Thử tìm với từ khóa khác hoặc bỏ bộ lọc.": "Try another keyword or remove filters.",
  "Nhập từ khóa để tìm sự kiện, cuộc họp, công việc...": "Enter keywords to search events, meetings, and tasks...",
  "Đã huỷ": "Cancelled",
  "Quá hạn": "Overdue",
  "Bình thường": "Normal",
  "Sắp xếp": "Sort",
  "Mới nhất": "Newest",
  "Cũ nhất": "Oldest",
  "Ưu tiên": "Priority",
  "Tên sự kiện": "Event name",
  "Thẻ": "Tags",
  "Thao tác": "Actions",
  "Không có lịch nào khớp bộ lọc.": "No schedules match the filters.",
  "Sửa": "Edit",
  "Xem chi tiết": "View details",
  "Hoàn thành tất cả": "Complete all",
  "Bỏ chọn": "Clear selection",
  "Trang trước": "Previous page",
  "Đang xoá...": "Deleting...",
  "Bảng điều khiển": "Dashboard",
  "Đánh dấu đã đọc tất cả": "Mark all as read",
  "Chưa đọc": "Unread",
  "Không có thông báo chưa đọc": "No unread notifications",
  "Vừa xong": "Just now",
  "Hôm qua": "Yesterday",
  "Xuất bảng tính đầy đủ, hỗ trợ tính toán và phân tích sâu.": "Export a full spreadsheet with calculation and analysis support.",
  "Tương thích hoàn hảo với Google Calendar, Outlook và Apple Calendar.": "Fully compatible with Google Calendar, Outlook, and Apple Calendar.",
  "Báo cáo lịch trình dạng in ấn, đẹp mắt và không thể chỉnh sửa.": "Printable schedule report, polished and read-only.",
  "Tùy chỉnh các thông số và định dạng tệp để lưu trữ hoặc chia sẻ lịch làm việc của bạn.": "Customize parameters and file formats to store or share your work schedule.",
  "Nội dung không được rỗng.": "Content cannot be empty.",
  "Gửi broadcast cho người dùng?": "Send broadcast to users?",
  "Soạn nội dung và gửi DM Mezon cho người dùng phù hợp với filter.": "Compose content and send Mezon DMs to users matching the filter.",
  "Nội dung": "Content",
  "Hệ thống sẽ bảo trì lúc 22h tối nay…": "The system will be under maintenance at 22:00 tonight...",
  "Lọc role": "Filter role",
  "User thường": "Regular user",
  "Bỏ qua user đã bị khoá": "Skip locked users",
  "Đang gửi…": "Sending...",
  "Gửi broadcast": "Send broadcast",
  "Người gửi": "Sender",
  "Lỗi": "Errors",
  "Chưa có broadcast nào.": "No broadcasts yet.",
  "Tên template và tiêu đề là bắt buộc.": "Template name and title are required.",
  "Tên template chỉ dùng chữ thường, số, dấu gạch ngang hoặc gạch dưới.": "Template name can only use lowercase letters, numbers, hyphens, or underscores.",
  "Đã cập nhật template.": "Template updated.",
  "Đã tạo template mới.": "New template created.",
  "Không thể lưu template.": "Could not save template.",
  "Không xoá được template.": "Could not delete template.",
  "Đã xoá template.": "Template deleted.",
  "Không thể xoá template.": "Could not delete template.",
  "Đã nhân bản template.": "Template duplicated.",
  "Không thể nhân bản template.": "Could not duplicate template.",
  "Mẫu lịch của tôi": "My schedule templates",
  "Tạo mẫu để điền nhanh tiêu đề, loại lịch, thời lượng và nhắc việc.": "Create templates to quickly fill title, schedule type, duration, and reminders.",
  "Tạo template mới": "Create new template",
  "Dùng ngay": "Use now",
  "Sửa template": "Edit template",
  "Nhân bản template": "Duplicate template",
  "Xoá template": "Delete template",
  "Thêm mẫu mới": "Add new template",
  "Lưu các cấu hình lịch thường dùng.": "Save commonly used schedule configurations.",
  "Chỉnh sửa template": "Edit template",
  "Tên template dùng chữ thường, ví dụ: daily-standup.": "Use lowercase template names, for example: daily-standup.",
  "Tên template": "Template name",
  "Thời lượng phút": "Duration minutes",
  "Nhắc trước phút": "Reminder minutes",
  "Lưu template": "Save template",
  "Quản lý lịch (toàn hệ thống)": "Manage schedules (system-wide)",
  "từ khoá": "keyword",
  "Quản trị viên": "Administrator",
  "Người dùng": "User",
  "Không lưu được hồ sơ": "Could not save profile",
  "Đã lưu hồ sơ": "Profile saved",
  "Đăng xuất thất bại": "Logout failed",
  "Đổi ảnh đại diện": "Change avatar",
  "Đã kết nối Mezon": "Mezon connected",
  "Thông tin cá nhân": "Personal information",
  "Họ và tên": "Full name",
  "Số điện thoại": "Phone number",
  "Chức vụ": "Job title",
  "Giới thiệu": "Bio",
  "Hoạt động gần đây": "Recent activity",
  "Tổng sự kiện": "Total events",
  "Đang thực hiện": "In progress",
  "Bảo mật": "Security",
  "Đăng nhập qua Mezon": "Sign in with Mezon",
  "Đang kết nối": "Connected",
  "Đăng xuất": "Log out",
  "Đã đánh dấu hoàn thành!": "Marked as completed!",
  "Không thể cập nhật trạng thái. Vui lòng thử lại.": "Could not update status. Please try again.",
  "Admin đã thay đổi thời gian kết thúc sự kiện từ 11:30 lên 12:00.": "Admin changed the event end time from 11:30 to 12:00.",
  "Bạn đã thêm tag \"Ưu tiên cao\" và đính kèm tệp tin.": "You added the \"High priority\" tag and attached a file.",
  "Sự kiện đã được tạo bởi Lê Văn A.": "Event was created by Le Van A.",
  "Trình bày báo cáo tài chính T9": "Present September financial report",
  "Phê duyệt ngân sách Marketing cho chiến dịch \"End-of-year\"": "Approve the marketing budget for the \"End-of-year\" campaign",
  "Quyết định nhân sự cấp cao cho dự án Cloud": "Decide senior staffing for the Cloud project",
  "Nhắc nhở": "Reminder",
  "Bạn có chắc muốn xóa": "Are you sure you want to delete",
  "Hành động này không thể hoàn tác. Tất cả dữ liệu liên quan sẽ bị xóa vĩnh viễn.": "This action cannot be undone. All related data will be permanently deleted.",
  "Hành động này không thể hoàn tác. Tất cả dữ liệu liên quan sẽ bị xoá vĩnh viễn.": "This action cannot be undone. All related data will be permanently deleted.",
  "Xóa lịch thành công!": "Schedule deleted successfully!",
  "Không thể xóa. Vui lòng thử lại.": "Could not delete. Please try again.",
  "Không thể xoá. Vui lòng thử lại.": "Could not delete. Please try again.",
  "Bảng điều khiển quản trị": "Admin dashboard",
  "Tổng quan KPI và xu hướng 30 ngày gần nhất": "Overview of KPIs and trends from the last 30 days",
  "Quản lý user": "Manage users",
  "Đang tải số liệu…": "Loading metrics...",
  "Tổng user": "Total users",
  "User mới hôm nay": "New users today",
  "Đang khoá": "Locked",
  "Tổng lịch": "Total schedules",
  "Lịch mới hôm nay": "New schedules today",
  "Tỷ lệ hoàn thành": "Completion rate",
  "Họp chiến lược Quý 2": "Q2 strategy meeting",
  "Thứ Hai 20/05/2025": "Monday 20/05/2025",
  "Họp nhóm hàng tuần": "Weekly team meeting",
  "Dự án Alpha": "Project Alpha",
  "Nguyễn Văn A": "Nguyen Van A",
  "Bạn sẽ không thể tạo nhanh lịch từ mẫu này nữa.": "You will no longer be able to quickly create schedules from this template.",
  "Các lịch trình vẫn được giữ nguyên nhưng sẽ không còn nhãn này.": "Schedules will remain unchanged but will no longer have this label.",
  "Chào mừng đến FocusFlow Pro!": "Welcome to FocusFlow Pro!",
  "Hãy cùng thiết lập không gian làm việc của bạn": "Let's set up your workspace",
  "Thiết lập giờ làm việc": "Set working hours",
  "Cho chúng tôi biết thời gian bạn thường xuyên hoạt động": "Tell us when you are usually active",
  "Tất cả đã sẵn sàng!": "Everything is ready!",
  "Bạn đã hoàn thành thiết lập ban đầu": "You have completed the initial setup",
  "Quản lý lịch trình": "Schedule management",
  "Tạo, sắp xếp và theo dõi các sự kiện hàng ngày": "Create, organize, and track daily events",
  "Nhắc nhở thông minh": "Smart reminders",
  "Không bao giờ bỏ lỡ sự kiện quan trọng": "Never miss an important event",
  "Thống kê năng suất": "Productivity statistics",
  "Hiểu rõ thời gian bạn sử dụng như thế nào": "Understand how you spend your time",
  "Bot Mezon tích hợp": "Integrated Mezon bot",
  "Quản lý lịch ngay trong Mezon chat": "Manage schedules directly in Mezon chat",
  "Chọn ngày làm việc": "Choose working days",
  "Kết nối tài khoản Mezon để nhận thông báo nhắc nhở, tạo lịch bằng lệnh chat, và đồng bộ danh bạ.": "Connect your Mezon account to receive reminders, create schedules with chat commands, and sync contacts.",
  "Bỏ qua bước này": "Skip this step",
  "Mọi thứ đã được thiết lập!": "Everything has been set up!",
  "Hãy bắt đầu tạo lịch trình đầu tiên của bạn.": "Start by creating your first schedule.",
  "Đi tới Dashboard": "Go to Dashboard",
  "Quay lại": "Back",
  "Hoàn tất": "Finish",
  "Tiếp tục": "Continue",
  "Người này sẽ không còn quyền xem hoặc chỉnh sửa lịch trình này ngay lập tức.": "This person will immediately lose permission to view or edit this schedule.",
  "Xoá thẻ": "Delete tag",
  "Không có lịch phù hợp.": "No matching schedules.",
  "Lúc 08:45": "At 08:45",
  "Sắp tới: Họp đầu tuần Team Marketing": "Upcoming: Weekly marketing team meeting",
  "Sự kiện bắt đầu trong 15 phút. Phòng họp 01, Tầng 3.": "The event starts in 15 minutes. Meeting room 01, 3rd floor.",
  "Trần Thị Bình đã chia sẻ lịch": "Tran Thi Binh shared a schedule",
  "Nhắc nhở: Deep Work": "Reminder: Deep Work",
  "Phiên tập trung cao sẽ bắt đầu lúc 14:00 hôm nay.": "The deep work session starts at 14:00 today.",
  "Hệ thống: Cập nhật thành công": "System: Update successful",
  "Cài đặt múi giờ đã được cập nhật thành Asia/Ho_Chi_Minh.": "Time zone settings were updated to Asia/Ho_Chi_Minh.",
  "Lịch đã được cập nhật": "Schedule updated",
  "Viết tài liệu API NestJS đã thay đổi mức ưu tiên thành Cao.": "NestJS API documentation changed priority to High.",
  "Nhắc nhở: Phỏng vấn ứng viên": "Reminder: Candidate interview",
  "Phỏng vấn Senior Designer lúc 10:00 ngày mai.": "Senior Designer interview at 10:00 tomorrow.",
  "Lê Hoàng Cường đã bình luận": "Le Hoang Cuong commented",
  "Đã thêm ghi chú vào Kick-off dự án SmartHome 2.0.": "Added a note to the SmartHome 2.0 kickoff.",
  "Hệ thống: Bảo trì định kỳ": "System: Scheduled maintenance",
  "Hệ thống sẽ bảo trì từ 02:00 - 04:00 ngày 26/10.": "The system will be under maintenance from 02:00 to 04:00 on 26/10.",
};

const hardcodedEnToVi = Object.fromEntries(
  Object.entries(hardcodedViToEn).map(([vi, en]) => [en, vi]),
) as Record<string, string>;

const viPatternTranslations: Array<[RegExp, string | ((match: RegExpMatchArray) => string)]> = [
  [/^Không có lịch nào trong (24h|7 ngày) tới$/, (m) => `No schedules in the next ${m[1] === "24h" ? "24h" : "7 days"}`],
  [/^Nhắc trước (\d+) phút$/, (m) => `Remind ${m[1]} minutes before`],
  [/^(\d+) phút trước khi bắt đầu$/, (m) => `${m[1]} minutes before start`],
  [/^1 giờ trước khi bắt đầu$/, "1 hour before start"],
  [/^1 ngày trước$/, "1 day before"],
  [/^Lặp mỗi (\d+) ngày$/, (m) => `Repeat every ${m[1]} days`],
  [/^Lặp mỗi (\d+) tuần$/, (m) => `Repeat every ${m[1]} weeks`],
  [/^Lặp mỗi (\d+) tháng$/, (m) => `Repeat every ${m[1]} months`],
  [/^Người tham gia \((\d+)\)$/, (m) => `Participants (${m[1]})`],
  [/^Tổng: (\d+) user\. Tìm theo user_id \/ username \/ display name\.$/, (m) => `Total: ${m[1]} users. Search by user_id / username / display name.`],
  [/^Sẽ xuất (\d+) lịch trình từ (.+) đến (.+)$/, (m) => `Will export ${m[1]} schedules from ${m[2]} to ${m[3]}`],
  [/^(\d+) ngày trước$/, (m) => `${m[1]} days before`],
  [/^(\d+) giờ trước$/, (m) => `${m[1]} hours before`],
  [/^(\d+) phút trước$/, (m) => `${m[1]} minutes before`],
  [/^Chuỗi (\d+) ngày liên tiếp!$/, (m) => `${m[1]} day streak!`],
  [/^Bạn đang làm rất tốt! Chỉ còn (\d+) mục tiêu nữa để hoàn thành kế hoạch tuần\.$/, (m) => `You are doing great. Only ${m[1]} more goals to complete this week's plan.`],
  [/^Mẫu "(.+)" sẽ bị xóa vĩnh viễn\.$/, (m) => `Template "${m[1]}" will be permanently deleted.`],
  [/^Bạn đang thực hiện xóa thẻ "(.+)"\.$/, (m) => `You are deleting the tag "${m[1]}".`],
  [/^Thẻ này sẽ bị gỡ bỏ khỏi (\d+) lịch trình hiện tại\.$/, (m) => `This tag will be removed from ${m[1]} current schedules.`],
  [/^Lịch được chia sẻ với tôi \((\d+)\)$/, (m) => `Schedules shared with me (${m[1]})`],
  [/^Tổng 30 ngày: (\d+)$/, (m) => `30-day total: ${m[1]}`],
  [/^Hoàn thành \((\d+)\)$/, (m) => `Completed (${m[1]})`],
  [/^(\d+) ngày streak$/, (m) => `${m[1]} day streak`],
  [/^\+(\d+)% so với tuần trước$/, (m) => `+${m[1]}% vs last week`],
  [/^(\d+)% tỷ lệ hoàn thành$/, (m) => `${m[1]}% completion rate`],
  [/^(\d+) dự án mới tháng này$/, (m) => `${m[1]} new projects this month`],
  [/^Đã chọn (\d+)$/, (m) => `${m[1]} selected`],
  [/^Hiển thị (.+) \/ (.+) lịch trình$/, (m) => `Showing ${m[1]} / ${m[2]} schedules`],
  [/^Xoá (\d+) lịch đã chọn\?$/, (m) => `Delete ${m[1]} selected schedules?`],
  [/^Đã hoàn thành (\d+) lịch$/, (m) => `${m[1]} schedules completed`],
  [/^Đã xoá (\d+) lịch$/, (m) => `${m[1]} schedules deleted`],
  [/^(\d+) thông báo chưa đọc$/, (m) => `${m[1]} unread notifications`],
  [/^Tất cả \((\d+)\)$/, (m) => `All (${m[1]})`],
  [/^Chưa đọc \((\d+)\)$/, (m) => `Unread (${m[1]})`],
  [/^Đã gửi cho (\d+) user\. Thành công: (\d+), lỗi: (\d+)\.$/, (m) => `Sent to ${m[1]} users. Success: ${m[2]}, errors: ${m[3]}.`],
  [/^Lịch sử broadcast \((\d+)\)$/, (m) => `Broadcast history (${m[1]})`],
  [/^Thời lượng: (\d+) phút$/, (m) => `Duration: ${m[1]} minutes`],
  [/^Nhắc trước: (\d+) phút$/, (m) => `Reminder: ${m[1]} minutes before`],
  [/^Tổng: (\d+) lịch$/, (m) => `Total: ${m[1]} schedules`],
  [/^Tổng: (\d+) bản ghi$/, (m) => `Total: ${m[1]} records`],
  [/^Đã lưu "(.+)"\.$/, (m) => `Saved "${m[1]}".`],
  [/^Bước (\d+) \/ (\d+)$/, (m) => `Step ${m[1]} / ${m[2]}`],
  [/^Mẫu "(.+)" sẽ bị xóa vĩnh viễn\.$/, (m) => `Template "${m[1]}" will be permanently deleted.`],
  [/^Bạn có chắc chắn muốn dừng chia sẻ lịch "(.+)" với (.+)\?$/, (m) => `Are you sure you want to stop sharing "${m[1]}" with ${m[2]}?`],
  [/^(.+) thông báo chưa đọc$/, (m) => `${m[1]} unread notifications`],
  [/^(.+) dự án mới tháng này$/, (m) => `${m[1]} new projects this month`],
];

function translateHardcodedText(text: string, language: Language): string {
  const trimmed = text.trim();
  if (!trimmed) return text;
  const dictionary = language === "en" ? hardcodedViToEn : hardcodedEnToVi;
  const exact = dictionary[trimmed];
  if (exact) return text.replace(trimmed, exact);
  if (language === "en") {
    for (const [pattern, replacement] of viPatternTranslations) {
      const match = trimmed.match(pattern);
      if (match) {
        const next =
          typeof replacement === "function" ? replacement(match) : replacement;
        return text.replace(trimmed, next);
      }
    }
  }
  const entries = Object.entries(dictionary)
    .filter(([from]) => from.length >= 4 && trimmed.includes(from))
    .sort((a, b) => b[0].length - a[0].length);
  if (entries.length > 0) {
    let translated = text;
    for (const [from, to] of entries) {
      translated = translated.split(from).join(to);
    }
    return translated;
  }
  return text;
}

function translateHardcodedDom(language: Language): void {
  if (typeof document === "undefined") return;
  const root = document.querySelector("[data-dashboard-shell]");
  if (!root) return;

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement;
      if (!parent) return NodeFilter.FILTER_REJECT;
      if (["SCRIPT", "STYLE", "TEXTAREA"].includes(parent.tagName)) {
        return NodeFilter.FILTER_REJECT;
      }
      return node.textContent?.trim()
        ? NodeFilter.FILTER_ACCEPT
        : NodeFilter.FILTER_REJECT;
    },
  });

  const textNodes: Text[] = [];
  while (walker.nextNode()) textNodes.push(walker.currentNode as Text);
  textNodes.forEach((node) => {
    const next = translateHardcodedText(node.textContent ?? "", language);
    if (next !== node.textContent) node.textContent = next;
  });

  root.querySelectorAll<HTMLElement>("[placeholder], [aria-label], [title]").forEach((el) => {
    for (const attr of ["placeholder", "aria-label", "title"]) {
      const value = el.getAttribute(attr);
      if (!value) continue;
      const next = translateHardcodedText(value, language);
      if (next !== value) el.setAttribute(attr, next);
    }
  });
}

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

function readStoredLanguage(): Language {
  if (typeof window === "undefined") return "vi";
  const stored = localStorage.getItem("language");
  if (stored === "vi" || stored === "en") return stored;
  return navigator.language.toLowerCase().startsWith("en") ? "en" : "vi";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("vi");

  useEffect(() => {
    setLanguageState(readStoredLanguage());
  }, []);

  const setLanguage = useCallback((next: Language) => {
    setLanguageState(next);
    try {
      localStorage.setItem("language", next);
    } catch {
      // Local persistence is best-effort.
    }
    document.documentElement.lang = next === "vi" ? "vi" : "en";
  }, []);

  useEffect(() => {
    document.documentElement.lang = language === "vi" ? "vi" : "en";
  }, [language]);

  useEffect(() => {
    let raf = 0;
    const run = () => {
      window.cancelAnimationFrame(raf);
      raf = window.requestAnimationFrame(() => translateHardcodedDom(language));
    };

    run();
    const root = document.querySelector("[data-dashboard-shell]");
    if (!root) return () => window.cancelAnimationFrame(raf);

    const observer = new MutationObserver(run);
    observer.observe(root, {
      attributes: true,
      childList: true,
      characterData: true,
      subtree: true,
    });

    return () => {
      window.cancelAnimationFrame(raf);
      observer.disconnect();
    };
  }, [language]);

  const t = useCallback(
    (key: string) => dictionaries[language][key] ?? dictionaries.vi[key] ?? key,
    [language],
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return ctx;
}
