import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "var(--md-surface)",
        "surface-dim": "var(--md-surface-dim)",
        "surface-bright": "var(--md-surface-bright)",
        "surface-container-lowest": "var(--md-surface-container-lowest)",
        "surface-container-low": "var(--md-surface-container-low)",
        "surface-container": "var(--md-surface-container)",
        "surface-container-high": "var(--md-surface-container-high)",
        "surface-container-highest": "var(--md-surface-container-highest)",
        "on-surface": "var(--md-on-surface)",
        "on-surface-variant": "var(--md-on-surface-variant)",
        "inverse-surface": "var(--md-inverse-surface)",
        "inverse-on-surface": "var(--md-inverse-on-surface)",
        outline: "var(--md-outline)",
        "outline-variant": "var(--md-outline-variant)",
        "surface-tint": "var(--md-surface-tint)",
        primary: "var(--md-primary)",
        "on-primary": "var(--md-on-primary)",
        "primary-container": "var(--md-primary-container)",
        "on-primary-container": "var(--md-on-primary-container)",
        "inverse-primary": "var(--md-inverse-primary)",
        secondary: "var(--md-secondary)",
        "on-secondary": "var(--md-on-secondary)",
        "secondary-container": "var(--md-secondary-container)",
        "on-secondary-container": "var(--md-on-secondary-container)",
        tertiary: "var(--md-tertiary)",
        "on-tertiary": "var(--md-on-tertiary)",
        "tertiary-container": "var(--md-tertiary-container)",
        "on-tertiary-container": "var(--md-on-tertiary-container)",
        error: "var(--md-error)",
        "on-error": "var(--md-on-error)",
        "error-container": "var(--md-error-container)",
        "on-error-container": "var(--md-on-error-container)",
        "primary-fixed": "var(--md-primary-fixed)",
        "primary-fixed-dim": "var(--md-primary-fixed-dim)",
        "secondary-fixed": "var(--md-secondary-fixed)",
        "secondary-fixed-dim": "var(--md-secondary-fixed-dim)",
        "tertiary-fixed": "var(--md-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--md-tertiary-fixed-dim)",
        "brand-charcoal": "#1A1A1B",
        "brand-teal": "#2D9CDB",
        "brand-orange": "#F2994A",
        "brand-ivory": "#FDF7FF",
        "lp-bg": "var(--lp-bg)",
        "lp-surface": "var(--lp-surface)",
        "lp-surface-dim": "var(--lp-surface-dim)",
        "lp-surface-container-lowest": "var(--lp-surface-container-lowest)",
        "lp-surface-container-low": "var(--lp-surface-container-low)",
        "lp-surface-container": "var(--lp-surface-container)",
        "lp-surface-container-high": "var(--lp-surface-container-high)",
        "lp-surface-container-highest": "var(--lp-surface-container-highest)",
        "lp-on-surface": "var(--lp-on-surface)",
        "lp-on-surface-variant": "var(--lp-on-surface-variant)",
        "lp-outline": "var(--lp-outline)",
        "lp-outline-variant": "var(--lp-outline-variant)",
        "lp-primary": "var(--lp-primary)",
        "lp-on-primary": "var(--lp-on-primary)",
        "lp-primary-container": "var(--lp-primary-container)",
        "lp-on-primary-container": "var(--lp-on-primary-container)",
        "lp-primary-fixed": "var(--lp-primary-fixed)",
        "lp-tertiary": "var(--lp-tertiary)",
        "lp-on-tertiary": "var(--lp-on-tertiary)",
        "lp-secondary": "var(--lp-secondary)",
        "lp-error": "var(--lp-error)",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "34px", fontWeight: "700" },
        ],
      },
      spacing: {
        unit: "4px",
        "topbar-height": "56px",
        "sidebar-width": "260px",
        "container-gap": "24px",
        "margin-page": "32px",
        "card-padding": "20px",
      },
    },
  },
  plugins: [],
};
export default config;
