import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#fdf7ff",
        "surface-dim": "#ded8e0",
        "surface-bright": "#fdf7ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f2fa",
        "surface-container": "#f2ecf4",
        "surface-container-high": "#ece6ee",
        "surface-container-highest": "#e6e0e9",
        "on-surface": "#1d1b20",
        "on-surface-variant": "#494551",
        "inverse-surface": "#322f35",
        "inverse-on-surface": "#f5eff7",
        outline: "#7a7582",
        "outline-variant": "#cbc4d2",
        "surface-tint": "#6750a4",
        primary: "#4f378a",
        "on-primary": "#ffffff",
        "primary-container": "#6750a4",
        "on-primary-container": "#e0d2ff",
        "inverse-primary": "#cfbcff",
        secondary: "#63597c",
        "on-secondary": "#ffffff",
        "secondary-container": "#e1d4fd",
        "on-secondary-container": "#645a7d",
        tertiary: "#765b00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c9a74d",
        "on-tertiary-container": "#503d00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#cfbcff",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#cdc0e9",
        "tertiary-fixed": "#ffdf93",
        "tertiary-fixed-dim": "#e7c365",
        "brand-charcoal": "#1A1A1B",
        "brand-teal": "#2D9CDB",
        "brand-orange": "#F2994A",
        "brand-ivory": "#FDF7FF",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "34px", fontWeight: "700" },
        ],
      },
      spacing: {
        unit: "4px",
        "topbar-height": "56px",
        "sidebar-width": "260px",
        "container-gap": "24px",
        "margin-page": "32px",
        "card-padding": "20px",
      },
    },
  },
  plugins: [],
};
export default config;
